# Generated by Django 4.0.4 on 2022-05-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='friend',
        ),
    ]
